export const SCRIPT_ID_PREFIX = "TCH";

export const ScriptIds = {
    CONTENT: `${SCRIPT_ID_PREFIX}_CONTENT`,
    INJECTED_MAIN: `${SCRIPT_ID_PREFIX}_INJECTED_MAIN`,
    INJECTED_INTERCEPTOR: `${SCRIPT_ID_PREFIX}_INJECTED_INTERCEPTOR`,
} as const;