export const SCRIPT_ID_PREFIX = "TCN_";

export const SCRIPT_IDS = {
    CONTENT: `${SCRIPT_ID_PREFIX}CONTENT`,
    INJECTED_MAIN: `${SCRIPT_ID_PREFIX}INJECTED_MAIN`,
    INJECTED_INTERCEPTOR: `${SCRIPT_ID_PREFIX}INJECTED_INTERCEPTOR`,
} as const;